---
group:
  # Using Bootstrap 5
  - files:
      # dotfiles to sync
      - .dockerignore
      - .editorconfig
      - .envrc
      - .gitignore
      - .yarnrc.yml
      - .sdkmanrc
      - .stylelintrc.mjs
      - eslint.config.mjs
      # GitHub Actions workflows
      - source: .github/workflows
        destination: .github/workflows
        exclude: |
          repo-files-sync.yml
      # Renovate bot configuration
      - source: .github/renovate.json5
        replace: false
      # Mergify configuration
      - .github/mergify.yml
      # Build files
      - source: lighthouserc.js
        replace: false
      - source: Dockerfile
        replace: false
      - detekt-config.yml
      - diktat-analysis.yml
      - micronaut-cli.yml
      # Build tasks
      - source: buildSrc/build.gradle.kts
        replace: false
      - buildSrc/src/main/kotlin/br/ufpe/liber/tasks
      # Shared source code
      - source: src/accessibilityTest/kotlin/br/ufpe/liber
        replace: false
      - src/main/kotlin/br/ufpe/liber/assets
      - src/main/kotlin/br/ufpe/liber/pagination
      - src/main/kotlin/br/ufpe/liber/Application.kt
      - src/main/kotlin/br/ufpe/liber/EagerInProduction.kt
      - src/main/kotlin/br/ufpe/liber/TemplatesFactory.kt
      - src/main/kotlin/br/ufpe/liber/controllers/AssetsController.kt
      - src/main/kotlin/br/ufpe/liber/controllers/DefaultExceptionHandler.kt
      - src/main/kotlin/br/ufpe/liber/controllers/ErrorsController.kt
      - src/main/kotlin/br/ufpe/liber/controllers/KteController.kt
      - src/main/kotlin/br/ufpe/liber/controllers/XContentTypeOptionsFilter.kt
      - src/main/kotlin/br/ufpe/liber/views/CSPHelper.kt
      - src/main/kotlin/br/ufpe/liber/views/ViewsHelper.kt
      - source: src/main/kotlin/br/ufpe/liber/views/LinksHelper.kt
        replace: false
      - src/main/resources/logback.xml
      - src/main/resources/base.conf
      - src/main/resources/public/images
      - src/test/kotlin/br/ufpe/liber/assets
      - src/test/kotlin/br/ufpe/liber/pagination
      - src/test/kotlin/br/ufpe/liber/views/ViewsHelperTest.kt
      - source: src/test/kotlin/br/ufpe/liber/views/LinksHelperTest.kt
        replace: false
      - src/test/kotlin/br/ufpe/liber/controllers/AssetsControllerTest.kt
      - src/test/kotlin/br/ufpe/liber/controllers/DefaultExceptionHandlerTest.kt
      - src/test/kotlin/br/ufpe/liber/controllers/ErrorsControllerTest.kt
      - src/test/kotlin/br/ufpe/liber/controllers/XContentTypeOptionsFilterTest.kt
      - source: src/test/kotlin/br/ufpe/liber/ApplicationTest.kt
        replace: false
      - src/test/kotlin/br/ufpe/liber/KteWritableExtensions.kt
      - src/test/kotlin/br/ufpe/liber/HttpClientExtensions.kt
      - src/test/kotlin/br/ufpe/liber/TemplatesFactoryTest.kt
      - src/test/kotlin/br/ufpe/liber/ProjectConfig.kt
      - src/test/resources/public/test-assets-metadata.json
      - src/main/jte/.jteroot
      - src/main/jte/assets
      # Some scripts
      - hooks/pre-commit
      # Others
      - LICENSE
    repos: |
      Liber-UFPE/visaoholandesa

  # Using Tailwind CSS
  - files:
      # dotfiles to sync
      - .dockerignore
      - .editorconfig
      - .envrc
      - .gitignore
      - .yarnrc.yml
      - .sdkmanrc
      - .stylelintrc.mjs
      - eslint.config.mjs
      # GitHub Actions workflows
      - source: .github/workflows
        destination: .github/workflows
        exclude: |
          repo-files-sync.yml
      # Renovate bot configuration
      - source: .github/renovate.json5
        replace: false
      # Mergify configuration
      - .github/mergify.yml
      # Build files
      - source: package.json
        replace: false
      - source: assets-pipeline.mjs
        replace: false
      - tailwind.config.js
      - source: lighthouserc.js
        replace: false
      - source: Dockerfile
        replace: false
      - detekt-config.yml
      - diktat-analysis.yml
      - micronaut-cli.yml
      # Build tasks
      - buildSrc/build.gradle.kts
      - buildSrc/src/main/kotlin/br/ufpe/liber/tasks
      # Shared source code
      - source: src/accessibilityTest/kotlin/br/ufpe/liber
        replace: false
      - src/main/kotlin/br/ufpe/liber/assets
      - src/main/kotlin/br/ufpe/liber/pagination
      - src/main/kotlin/br/ufpe/liber/Application.kt
      - src/main/kotlin/br/ufpe/liber/EagerInProduction.kt
      - src/main/kotlin/br/ufpe/liber/TemplatesFactory.kt
      - src/main/kotlin/br/ufpe/liber/controllers/AssetsController.kt
      - src/main/kotlin/br/ufpe/liber/controllers/DefaultExceptionHandler.kt
      - src/main/kotlin/br/ufpe/liber/controllers/ErrorsController.kt
      - src/main/kotlin/br/ufpe/liber/controllers/KteController.kt
      - src/main/kotlin/br/ufpe/liber/controllers/XContentTypeOptionsFilter.kt
      - src/main/kotlin/br/ufpe/liber/views/CSPHelper.kt
      - src/main/kotlin/br/ufpe/liber/views/ViewsHelper.kt
      - source: src/main/kotlin/br/ufpe/liber/views/LinksHelper.kt
        replace: false
      - src/main/resources/logback.xml
      - src/main/resources/base.conf
      - src/main/resources/public/images
      - src/test/kotlin/br/ufpe/liber/assets
      - src/test/kotlin/br/ufpe/liber/pagination
      - src/test/kotlin/br/ufpe/liber/views/ViewsHelperTest.kt
      - source: src/test/kotlin/br/ufpe/liber/views/LinksHelperTest.kt
        replace: false
      - src/test/kotlin/br/ufpe/liber/controllers/AssetsControllerTest.kt
      - src/test/kotlin/br/ufpe/liber/controllers/DefaultExceptionHandlerTest.kt
      - src/test/kotlin/br/ufpe/liber/controllers/ErrorsControllerTest.kt
      - src/test/kotlin/br/ufpe/liber/controllers/XContentTypeOptionsFilterTest.kt
      - source: src/test/kotlin/br/ufpe/liber/ApplicationTest.kt
        replace: false
      - src/test/kotlin/br/ufpe/liber/KteWritableExtensions.kt
      - src/test/kotlin/br/ufpe/liber/HttpClientExtensions.kt
      - src/test/kotlin/br/ufpe/liber/TemplatesFactoryTest.kt
      - src/test/kotlin/br/ufpe/liber/ProjectConfig.kt
      - src/test/resources/public/test-assets-metadata.json
      - src/main/jte/.jteroot
      - src/main/jte/assets
      - src/main/jte/partials/content-section.kte
      - src/main/jte/partials/error.kte
      - src/main/jte/partials/main-section.kte
      - source: src/main/jte/partials/pagination.kte
        replace: false
      - source: src/main/jte/partials/navlink.kte
        replace: false
      - src/main/jte/internalServerError.kte
      - src/main/jte/notFound.kte
      # Some scripts
      - hooks/pre-commit
      # Others
      - LICENSE
    repos: |
      Liber-UFPE/hyginia
      Liber-UFPE/pereira-da-costa
