name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  compile:
    name: Build / compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Liber-UFPE/spring-gradle-build-action@v1
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run testCompile
        run: ./gradlew compileTestKotlin

  detekt:
    name: Code Analysis / detekt
    runs-on: ubuntu-latest
    needs:
      - compile
    steps:
      - uses: actions/checkout@v4
      - name: detekt report
        uses: natiginfo/action-detekt-all@1.23.1
        with:
          args: |
            --report md:build/reports/detekt/detekt.md
      - name: Detekt Summary
        run: cat build/reports/detekt/detekt.md >> $GITHUB_STEP_SUMMARY

  ktlint:
    name: Code Analysis / ktlint
    runs-on: ubuntu-latest
    needs:
      - compile
    steps:
      - uses: actions/checkout@v4
      - uses: nbadal/action-ktlint-setup@v1
      - name: ktlint version
        run: ktlint --version
      - name: run ktlin
        run: ktlint --relative >> $GITHUB_STEP_SUMMARY

#  diktat:
#    name: Code Analysis / diktat
#    runs-on: ubuntu-latest
#    needs:
#      - compile
#    steps:
#      - uses: actions/checkout@v4
#      - uses: Liber-UFPE/spring-gradle-build-action@v1
#      - name: Run diktatCheck
#        run: ./gradlew diktatCheck mergeDiktatReports

  test:
    name: Tests / test
    runs-on: ubuntu-latest
    needs:
      - detekt
      - ktlint
      # - diktat
    steps:
      - uses: actions/checkout@v4
      - uses: Liber-UFPE/spring-gradle-build-action@v1
      - name: Run tests
        run: ./gradlew test
      - name: Coverage HTML Report
        run: ./gradlew koverHtmlReport
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Output Kover summary
        # Adapted from https://github.com/Kotlin/kotlinx-kover/issues/419#issuecomment-1632572084
        run: |
          pandoc build/reports/kover/html/index.html -f html -t gfm | \
            sed -n '/# project-starter: Overall Coverage Summary/,/<\/div>/p' | \
            grep -v "</div>" >> $GITHUB_STEP_SUMMARY
      - name: Test Summary Report
        uses: phoenix-actions/test-reporting@v12
        if: always()
        with:
          name: Kotest Report
          path: "build/test-results/test/TEST-*.xml"
          reporter: java-junit
          output-to: "step-summary"
          only-summary: "true"

  build:
    name: Package / build
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: Liber-UFPE/spring-gradle-build-action@v1
      - name: Run build
        run: ./gradlew build

  build-docker:
    name: Package / Docker / build
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: Liber-UFPE/spring-gradle-build-action@v1
      - name: Run dockerBuild
        run: ./gradlew dockerBuild
