---
name: Sync Files

# yamllint disable rule:truthy
on:
  schedule:
    # At 23:59 on Friday.
    - cron: "59 23 * * FRI"
# yamllint enable rule:truthy

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run GitHub File Sync
        uses: Liber-UFPE/repo-file-sync-action@v1.22.2
        with:
          GH_PAT: ${{ secrets.REPO_SYNC_PAT }}
          COMMIT_EACH_FILE: false  # Commit all files at once
          PR_LABELS: |
            file-sync
