name: Sync Files

on:
  workflow_run:
    types: [ completed ]
    workflows: [ CI ]
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run GitHub File Sync
        uses: Liber-UFPE/repo-file-sync-action@v1.22.0
        with:
          GH_PAT: ${{ secrets.REPO_SYNC_PAT }}
          COMMIT_EACH_FILE: false # Commit all files at once
